version: "2"

networks:
  benri-net:
    external:
      name: benri-net

services:
  jira-exporter:
    container_name: jira-exporter
    build: .
    tty: true
    stdin_open: true
    expose:
      - 9171
    networks:
      - benri-net
    ports:
      - 9171:9171
    env_file:
      - .env
  
